create table users(
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    created_by bigint, -- Only not-null created_by across all db
    updated_at timestamptz,
    updated_by bigint,
    name varchar(100) not null,
    email varchar(100) not null unique,
    hashed_password character varying(60) not null  
);

insert into users (name, email, hashed_password) values ('Sergio Valdez', 'email@email.com', 'abc123');

create table meal_types(
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    created_by bigint not null,
    updated_at timestamptz,
    updated_by bigint,
    name varchar(20) not null
);

insert into meal_types (created_by, name) values (1, 'Breakfast');
insert into meal_types (created_by, name) values (1, 'Lunch');
insert into meal_types (created_by, name) values (1, 'Dinner');
insert into meal_types (created_by, name) values (1, 'Snack');

-- create table custom_meal_types(
--     id bigint generated by default as identity primary key,
--     created_at timestamptz not null default now(),
--     created_by bigint not null,
--     updated_at timestamptz,
--     updated_by bigint,
--     user_id bigint not null references users(id),
--     meal_id bigint references meal_types(id),
--     name varchar(20) not null,
--     is_editable boolean not null,
--     ord smallint
-- );

create table meals(
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    created_by bigint not null,
    updated_at timestamptz,
    updated_by bigint,
    user_id bigint not null references users(id),
    meal_type_id bigint not null references meal_types(id),
    date timestamptz
);

create table meals(
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    created_by bigint not null,
    updated_at timestamptz,
    updated_by bigint,
    user_id bigint not null references users(id),
    meal_type_id bigint not null references meal_types(id),
    date timestamptz
);

create table foods(
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    created_by bigint not null,
    updated_at timestamptz,
    updated_by bigint,
    kcal smallint,
    carbs smallint,
    proteins smallint,
    fats smallint
);

create table custom_foods(
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    created_by bigint not null,
    updated_at timestamptz,
    updated_by bigint,
    user_id bigint not null references meals(id),
    kcal smallint,
    carbs smallint,
    proteins smallint,
    fats smallint
);

create table meal_foods(
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    created_by bigint not null,
    updated_at timestamptz,
    updated_by bigint,
    meal_id bigint not null references meals(id),
    food_id bigint references foods(id),
    custom_food_id bigint references custom_foods(id)
);