create table users(
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    created_by bigint, -- Only not-null created_by across all db
    updated_at timestamptz,
    updated_by bigint,
    name varchar(100) not null,
    email varchar(100) not null unique,
    hashed_password character varying(60) not null  
);

insert into users (name, email, hashed_password) values ('Sergio Valdez', 'email@email.com', 'abc123');

create table meal_types(
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    created_by bigint not null,
    updated_at timestamptz,
    updated_by bigint,
    name varchar(20) not null
);

insert into meal_types (created_by, name) values (1, 'Breakfast');
insert into meal_types (created_by, name) values (1, 'Lunch');
insert into meal_types (created_by, name) values (1, 'Dinner');
insert into meal_types (created_by, name) values (1, 'Snack');

create table foods(
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    created_by bigint not null,
    updated_at timestamptz,
    updated_by bigint,
    name varchar(100) not null unique,
    description varchar(200),
    kcal numeric(6, 2),
    carbs numeric(6, 2),
    proteins numeric(6, 2),
    fats numeric(6, 2),
    sodium numeric(6, 2),
    active boolean not null default true
);

create table custom_foods(
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    created_by bigint not null,
    updated_at timestamptz,
    updated_by bigint,
    user_id bigint not null references users(id),
    name varchar(100) not null,
    kcal numeric(6, 2),
    carbs numeric(6, 2),
    proteins numeric(6, 2),
    fats numeric(6, 2),
    sodium numeric(6, 2)
);

create table meal_foods(
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    created_by bigint not null,
    updated_at timestamptz,
    updated_by bigint,
    user_id bigint not null references users(id),
    meal_type_id bigint not null references meal_types(id),
    date timestamptz not null,
    food_id bigint references foods(id),
    custom_food_id bigint references custom_foods(id),
    qty numeric(6, 2)
);